- name: Install Fedora specific packages
  when: ansible_distribution == 'Fedora'
  ansible.builtin.package:
    name:
      - yum-plugin-priorities
      - epel-release

- name: Install desktop Software
  ansible.builtin.package:
    name:
      - bmon
      - build-essential
      - chrome-gnome-shell
      - chromium-browser
      - curl
      - firefox
      - forensics-all
      - gcc
      - git
      - gimp
      - gnome
      - gnome-tweaks
      - golang-go
      - golint
      - grep
      - htop
      - inotify-tools
      - iotop
      - jq
      - libcanberra-gtk-module
      - make
      - mycli
      - nautilus-admin
      - nautilus-extension-gnome-terminal
      - nautilus-font-manager
      - nautilus-image-converter
      - nautilus-wipe
      - ncdu
      - neofetch # get system deets to flex on others
      - nethogs
      - net-tools
      - nmap
      - pandoc
      - pass
      - powertop
      - pwgen
      - python3-pip
      - shellcheck
      - socat
      - tar
      - terminator
      - tig
      - tmux
      - tree
      - ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
      - unzip
      - wget
      - whois
      - vim
      - vim-pathogen
      - vim-gtk3
      - vim-syntastic
      - vim-syntax-docker
      - vlc
      - xclip # to manipulate the clipboard
      - zip
      - zsh
      - zsh-syntax-highlighting
    state: latest

- name: Install python packages
  pip:
    name:
      #- aws-cli
      - termtime
      - bpytop
